CREATE DATABASE my_database;

USE my_database;

CREATE TABLE REVIEW 
(
  ID VARCHAR2(20) NOT NULL 
, UPDATED_AT DATE 
, CREATED_AT DATE 
, USER_ID VARCHAR2(20) 
, PLACE_ID VARCHAR2(20) 
, TEXT VARCHAR2(20) 
, CONSTRAINT REVIEW_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE PLACE 
(
  ID VARCHAR2(20) NOT NULL 
, UPDATED_AT DATE 
, CREATED_AT DATE 
, USER_ID VARCHAR2(20) 
, NAME VARCHAR2(20) 
, CITY_ID VARCHAR2(20) 
, NUMBER_ROOMS NUMBER DEFAULT 0 
, NUMBER_BATHROOMS NUMBER DEFAULT 0 
, MAX_GUEST NUMBER DEFAULT 0 
, PRICE_BY_NIGTH NUMBER DEFAULT 0 
, CONSTRAINT PLACE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE USUARIO 
(
  ID VARCHAR2(20) NOT NULL 
, UPDATED_AT DATE 
, CREATED_AT DATE 
, EMAIL VARCHAR2(20) 
, PASSWORD VARCHAR2(20) 
, CONSTRAINT USUARIO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


CREATE TABLE STATE 
(
  ID VARCHAR2(20) NOT NULL 
, UPDATED_AT DATE 
, CREATED_AT DATE 
, NAME VARCHAR2(20) 
, CONSTRAINT STATE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


CREATE TABLE CITY 
(
  ID VARCHAR2(20) NOT NULL 
, UPDATED_AT DATE 
, CREATED_AT DATE 
, STATE_ID VARCHAR2(20) 
, NAME VARCHAR2(20) 
, CONSTRAINT CITY_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


CREATE TABLE AMENITY 
(
  ID VARCHAR2(20) NOT NULL 
, UPDATED_AT DATE 
, CREATED_AT DATE 
, NAME VARCHAR2(20) 
, CONSTRAINT AMENITY_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE PLACE_AMENITY 
(
  AMENITY_ID VARCHAR2(20) NOT NULL 
, PLACE_ID VARCHAR2(20) 
);


ALTER TABLE Review ADD FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID);
ALTER TABLE Review ADD FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID);
ALTER TABLE Place ADD FOREIGN KEY (USER_ID) REFERENCES USUARIO(ID);
ALTER TABLE Place ADD FOREIGN KEY (CITY_ID) REFERENCES CITY(ID);
ALTER TABLE Place_Amenity ADD FOREIGN KEY (AMENITY_ID) REFERENCES AMENITY(ID);
ALTER TABLE Place_Amenity ADD FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID);
ALTER TABLE CITY ADD FOREIGN KEY (STATE_ID) REFERENCES STATE(ID);